// Optimizes the raw photos in public/assets into web-sized login slides.
//
//   public/assets/*.{jpg,jpeg,png,webp}  ->  public/slides/slide-NN.jpg        (1600px wide)
//                                            public/slides/thumb/slide-NN.jpg  (420x420 crop)
//   and regenerates src/lib/login-slides.ts
//
// Usage: node scripts/optimize-slides.mjs
//
// HEIC/HEIF photos are used only if the optional `heic-convert` package is installed
// (npm i -D heic-convert); otherwise they are skipped with a warning. Tip: export iPhone
// photos as JPEG ("Most Compatible") or convert them first.
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(root, "public", "assets");
const OUT = path.join(root, "public", "slides");
const THUMBS = path.join(OUT, "thumb");
const MANIFEST = path.join(root, "src", "lib", "login-slides.ts");

const WIDTH = 1600;
const QUALITY = 72;
const THUMB_SIZE = 420;
const THUMB_QUALITY = 60;

const NATIVE = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const HEIC = new Set([".heic", ".heif"]);

let heicConvert = null;
try { heicConvert = (await import("heic-convert")).default; } catch { /* optional */ }

async function load(file) {
  const ext = path.extname(file).toLowerCase();
  const full = path.join(SRC, file);
  if (NATIVE.has(ext)) return sharp(full);
  if (HEIC.has(ext)) {
    if (!heicConvert) return null;
    const jpeg = await heicConvert({ buffer: await readFile(full), format: "JPEG", quality: 0.9 });
    return sharp(Buffer.from(jpeg));
  }
  return null;
}

const files = (await readdir(SRC)).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

await rm(OUT, { recursive: true, force: true });
await mkdir(THUMBS, { recursive: true });

const slides = [];
const skipped = [];
let n = 0;

for (const file of files) {
  try {
    const img = await load(file);
    if (!img) { skipped.push(file); continue; }
    n += 1;
    const name = `slide-${String(n).padStart(2, "0")}.jpg`;
    const base = img.rotate(); // respect EXIF orientation
    await base.clone()
      .resize({ width: WIDTH, withoutEnlargement: true })
      .jpeg({ quality: QUALITY, mozjpeg: true })
      .toFile(path.join(OUT, name));
    await base.clone()
      .resize(THUMB_SIZE, THUMB_SIZE, { fit: "cover" })
      .jpeg({ quality: THUMB_QUALITY, mozjpeg: true })
      .toFile(path.join(THUMBS, name));
    slides.push(name);
    console.log(`✓ ${file} -> ${name}`);
  } catch (err) {
    n -= 1;
    skipped.push(file);
    console.warn(`✗ ${file}: ${err.message}`);
  }
}

const list = arr => arr.map(s => `  "${s}"`).join(",\n");
await writeFile(
  MANIFEST,
  `// Generated by scripts/optimize-slides.mjs\n` +
  `export const LOGIN_SLIDES: string[] = [\n${list(slides.map(s => `/slides/${s}`))}\n];\n` +
  `export const LOGIN_THUMBS: string[] = [\n${list(slides.map(s => `/slides/thumb/${s}`))}\n];\n`,
);

console.log(`\nDone: ${slides.length} slides written.`);
if (skipped.length) {
  console.warn(`Skipped ${skipped.length} file(s)${heicConvert ? "" : " (HEIC needs: npm i -D heic-convert)"}:`);
  skipped.forEach(f => console.warn(`  - ${f}`));
}
